/** Costante per la label delle CTA ( Click to action ) */
export const BUTTON_CONSTANT = {
  login: 'LOGIN',
  invia_email: 'SEND EMAIL',
  go_to_login: 'GO TO LOGIN',
  annulla: 'ANNULLA',
  avanti: 'AVANTI',
  conferma: 'CONFERMA',
  esci: 'ESCI',
  indietro: 'INDIETRO',
  salva_modifiche: 'SALVA MODIFICHE',
  salva: 'SALVA',
  applica: 'APPLICA',
  aggiungi: 'AGGIUNGI',
  aggiungi_casa: 'AGGIUNGI CASA',
  elimina: 'ELIMINA',
  modifica_casa: 'MODIFICA CASA',
  assegna_casa: 'ASSEGNA CASA',
  aggiungi_locatore: 'AGGIUNGI LOCATORE',
  aggiungi_inquilino: 'AGGIUNGI INQUILINO',
  crea_locatore: 'CREA LOCATORE',
  crea_inquilino: 'CREA INQUILINO',
  dettaglio: 'DETTAGLIO',
  modifica_profilo: 'MODIFICA PROFILO',
};
