import { NoopScrollStrategy } from '@angular/cdk/overlay';

import { BUTTON_CONSTANT } from './button.constant';
import { ICON_CONSTANT } from './icon.constant';
import { LABEL_CONSTANT } from './label.constant';

/** Config per la GenericConfirmModal */
export const GENERIC_CONFIRM = {
  // elimina_coltura: {
  //   width: '548px',
  //   height: '280px',
  //   autoFocus: false,
  //   scrollStrategy: new NoopScrollStrategy(),
  //   data: {
  //     title: LABEL_CONSTANT.sicuro_di_eliminare_coltura,
  //     subtitle: LABEL_CONSTANT.dati_colture,
  //     buttonText: BUTTON_CONSTANT.elimina,
  //     buttonType: 'warn',
  //     dimension: 'sm',
  //   },
  // },
  sicuro_di_uscire: {
    width: '548px',
    height: '280px',
    autoFocus: false,
    scrollStrategy: new NoopScrollStrategy(),
    data: {
      title: LABEL_CONSTANT.sicuro_di_uscire,
      subtitle: LABEL_CONSTANT.modifiche_non_salvate,
      buttonText: BUTTON_CONSTANT.esci,
      buttonType: 'primary',
      dimension: 'sm',
    },
  },
  effettua_logout: {
    width: '548px',
    height: '280px',
    autoFocus: false,
    scrollStrategy: new NoopScrollStrategy(),
    data: {
      title: LABEL_CONSTANT.effettua_logout,
      subtitle: LABEL_CONSTANT.conferma_logout,
      buttonText: BUTTON_CONSTANT.conferma,
      buttonType: 'primary',
      dimension: 'sm',
    },
  },
  // elimina_gestore: {
  //   width: '548px',
  //   height: '280px',
  //   autoFocus: false,
  //   scrollStrategy: new NoopScrollStrategy(),
  //   data: {
  //     title: LABEL_CONSTANT.vuoi_eliminare_gestore,
  //     subtitle: LABEL_CONSTANT.tutti_i_dati_coltivatore,
  //     buttonText: BUTTON_CONSTANT.elimina,
  //     buttonType: 'warn',
  //     dimension: 'sm',
  //   },
  // },
  // elimina_coltivatore: {
  //   width: '548px',
  //   height: '280px',
  //   autoFocus: false,
  //   scrollStrategy: new NoopScrollStrategy(),
  //   data: {
  //     title: LABEL_CONSTANT.vuoi_eliminare_coltivatore,
  //     subtitle: LABEL_CONSTANT.tutti_i_dati_coltivatore,
  //     buttonText: BUTTON_CONSTANT.elimina,
  //     buttonType: 'warn',
  //     dimension: 'sm',
  //   },
  // },
  // elimina_zona: {
  //   width: '548px',
  //   height: '280px',
  //   autoFocus: false,
  //   scrollStrategy: new NoopScrollStrategy(),
  //   data: {
  //     title: LABEL_CONSTANT.vuoi_eliminare_zona,
  //     subtitle: LABEL_CONSTANT.tutti_i_dati_zona,
  //     buttonText: BUTTON_CONSTANT.elimina,
  //     buttonType: 'warn',
  //     dimension: 'sm',
  //   },
  // },
  // elimina_campo: {
  //   width: '548px',
  //   height: '280px',
  //   autoFocus: false,
  //   scrollStrategy: new NoopScrollStrategy(),
  //   data: {
  //     title: LABEL_CONSTANT.vuoi_eliminare_campo,
  //     subtitle: LABEL_CONSTANT.tutti_i_dati_campo,
  //     buttonText: BUTTON_CONSTANT.elimina,
  //     buttonType: 'warn',
  //     dimension: 'sm',
  //   },
  // },
  // elimina_trasformazione: {
  //   width: '548px',
  //   height: '280px',
  //   autoFocus: false,
  //   scrollStrategy: new NoopScrollStrategy(),
  //   data: {
  //     title: LABEL_CONSTANT.vuoi_eliminare_trasformazione,
  //     subtitle: LABEL_CONSTANT.tutti_i_dati_trasformazione,
  //     buttonText: BUTTON_CONSTANT.elimina,
  //     buttonType: 'warn',
  //     dimension: 'sm',
  //   },
  // },
};

/** Config per la GenericFeedbackModal */
export const GENERIC_FEEDBACK = {
  crea_casa: {
    width: '548px',
    height: '280px',
    scrollStrategy: new NoopScrollStrategy(),
    data: {
      titolo: LABEL_CONSTANT.casa_creata,
      subtitle: LABEL_CONSTANT.dati_casa_creata,
      icona: ICON_CONSTANT.done,
      tipo: 'circle',
      status: 'success',
      dimensione: 'sm',
      autoCloseTime: 3000,
    },
  },
  // eliminazione_coltura: {
  //   width: '548px',
  //   height: '280px',
  //   scrollStrategy: new NoopScrollStrategy(),
  //   data: {
  //     titolo: LABEL_CONSTANT.coltura_eliminata,
  //     subtitle: LABEL_CONSTANT.dati_coltura_eliminati,
  //     icona: 'delete',
  //     tipo: 'circle',
  //     status: 'error',
  //     dimensione: 'sm',
  //     autoCloseTime: 3000,
  //   },
  // },
  // crea_gestore: {
  //   width: '548px',
  //   height: '280px',
  //   scrollStrategy: new NoopScrollStrategy(),
  //   data: {
  //     titolo: LABEL_CONSTANT.gestore_creato,
  //     subtitle: LABEL_CONSTANT.mess_mail_creazione,
  //     icona: ICON_CONSTANT.done,
  //     tipo: 'circle',
  //     status: 'success',
  //     dimensione: 'sm',
  //     autoCloseTime: 3000,
  //   },
  // },
  // crea_coltivatore: {
  //   width: '548px',
  //   height: '280px',
  //   scrollStrategy: new NoopScrollStrategy(),
  //   data: {
  //     titolo: LABEL_CONSTANT.coltivatore_creato,
  //     subtitle: LABEL_CONSTANT.mess_mail_creazione,
  //     icona: ICON_CONSTANT.done,
  //     tipo: 'circle',
  //     status: 'success',
  //     dimensione: 'sm',
  //     autoCloseTime: 3000,
  //   },
  // },
  modifiche_salvate: {
    width: '548px',
    height: '280px',
    scrollStrategy: new NoopScrollStrategy(),
    data: {
      // titolo: LABEL_CONSTANT.salvataggio_modifiche,
      // subtitle: LABEL_CONSTANT.modifiche_salvate_correttamente,
      icona: ICON_CONSTANT.done,
      tipo: 'circle',
      status: 'success',
      dimensione: 'sm',
      autoCloseTime: 3000,
    },
  },
  // modifiche_effettuate: {
  //   width: '548px',
  //   height: '280px',
  //   scrollStrategy: new NoopScrollStrategy(),
  //   data: {
  //     titolo: LABEL_CONSTANT.modifiche_effettuate,
  //     subtitle: LABEL_CONSTANT.modifiche_salvate_correttamente,
  //     icona: ICON_CONSTANT.done,
  //     tipo: 'circle',
  //     status: 'success',
  //     dimensione: 'sm',
  //     autoCloseTime: 3000,
  //   },
  // },
  // password_modificata: {
  //   width: '548px',
  //   height: '280px',
  //   scrollStrategy: new NoopScrollStrategy(),
  //   data: {
  //     titolo: LABEL_CONSTANT.password_modifcata,
  //     subtitle: LABEL_CONSTANT.hai_aggiornato_correttamente_la_password,
  //     icona: 'done',
  //     tipo: 'circle',
  //     status: 'success',
  //     dimensione: 'sm',
  //     autoCloseTime: 3000,
  //   },
  // },
  // zona_creata: {
  //   width: '548px',
  //   height: '280px',
  //   scrollStrategy: new NoopScrollStrategy(),
  //   data: {
  //     titolo: LABEL_CONSTANT.zona_creata,
  //     subtitle: LABEL_CONSTANT.zona_creata_subtitle,
  //     icona: 'done',
  //     tipo: 'circle',
  //     status: 'success',
  //     dimensione: 'sm',
  //     autoCloseTime: 3000,
  //   },
  // },
  // eliminazione_gestore_effettuata: {
  //   width: '548px',
  //   height: '280px',
  //   scrollStrategy: new NoopScrollStrategy(),
  //   data: {
  //     titolo: LABEL_CONSTANT.gestore_eliminato,
  //     subtitle: LABEL_CONSTANT.conferma_eliminazione_gestore,
  //     icona: 'delete',
  //     tipo: 'circle',
  //     status: 'error',
  //     dimensione: 'sm',
  //     autoCloseTime: 3000,
  //   },
  // },
  // eliminazione_coltivatore_effettuata: {
  //   width: '548px',
  //   height: '280px',
  //   scrollStrategy: new NoopScrollStrategy(),
  //   data: {
  //     titolo: LABEL_CONSTANT.coltivatore_eliminato,
  //     subtitle: LABEL_CONSTANT.conferma_eliminazione_coltivatore,
  //     icona: 'delete',
  //     tipo: 'circle',
  //     status: 'error',
  //     dimensione: 'sm',
  //     autoCloseTime: 3000,
  //   },
  // },
  // eliminazione_zona_effettuata: {
  //   width: '548px',
  //   height: '280px',
  //   scrollStrategy: new NoopScrollStrategy(),
  //   data: {
  //     titolo: LABEL_CONSTANT.zona_eliminata,
  //     subtitle: LABEL_CONSTANT.conferma_eliminazione_zona,
  //     icona: 'delete',
  //     tipo: 'circle',
  //     status: 'error',
  //     dimensione: 'sm',
  //     autoCloseTime: 3000,
  //   },
  // },
  // eliminazione_campo_effettuata: {
  //   width: '548px',
  //   height: '280px',
  //   scrollStrategy: new NoopScrollStrategy(),
  //   data: {
  //     titolo: LABEL_CONSTANT.campo_eliminato,
  //     subtitle: LABEL_CONSTANT.conferma_eliminazione_campo,
  //     icona: 'delete',
  //     tipo: 'circle',
  //     status: 'error',
  //     dimensione: 'sm',
  //     autoCloseTime: 3000,
  //   },
  // },
  // avvia_coltivazione: {
  //   width: '548px',
  //   height: '280px',
  //   scrollStrategy: new NoopScrollStrategy(),
  //   data: {
  //     titolo: LABEL_CONSTANT.coltivazione_creata,
  //     subtitle: LABEL_CONSTANT.coltivazione_creata_subtitle,
  //     icona: ICON_CONSTANT.done,
  //     tipo: 'circle',
  //     status: 'success',
  //     dimensione: 'sm',
  //     autoCloseTime: 3000,
  //   },
  // },
  // eliminazione_trasformazione: {
  //   width: '548px',
  //   height: '280px',
  //   scrollStrategy: new NoopScrollStrategy(),
  //   data: {
  //     titolo: LABEL_CONSTANT.trasformazione_eliminata,
  //     subtitle: LABEL_CONSTANT.conferma_eliminazione_trasformazione,
  //     icona: 'delete',
  //     tipo: 'circle',
  //     status: 'error',
  //     dimensione: 'sm',
  //     autoCloseTime: 3000,
  //   },
  // },
};
