export const LABEL_CONSTANT = {
  login: 'Login',
  email: 'Email',
  password: 'Password',
  repetPassword: 'Repet password',
  forgot_password: 'Forgot password',
  insert_password: 'Insert a new password',
  new_password: 'New Password',
  welcome: 'Welcome',
  to_website: 'to our new website!',
  send_email: 'An email will be sent to you with steps to follow',
  loading: 'Loading',
  dashboard: 'Dashboard',
  case: 'Case',
  allestimenti: 'Allestimenti',
  prenotazioni: 'Prenotazioni',
  statistiche: 'Statistiche',
  logout: 'Logout',
  profilo: 'Profilo',
  sicuro_di_uscire: 'Vuoi uscire?',
  modifiche_non_salvate: 'I dati inseriti andranno persi.',
  effettua_logout: 'Effettua Logout',
  conferma_logout: 'Sei sicuro di voler effettuare il logout?',
  elimina: 'Elimina',
  aggiungi_casa: 'AGGIUNGI CASA',
  inserisci_dati: 'Inserisci i dati.',
  statoAffitto: 'Stato del affitto',
  statoManutenzione: 'Stato manutenzione',
  arredata: 'Arredata',
  piano: 'Piano',
  tipoRiscaldamento: 'Tipo di riscaldamento',
  giardino: 'Giardino',
  postoAuto: 'Posto auto',
  ariaCondizionata: 'Aria condizionata',
  metodoPagamento: 'Metodo di pagamento',
  trascina_qui: 'Trascina qui le tue immagini o clicca per caricare',
  casa_creata: 'Casa creata correttamente!',
  dati_casa_creata: 'Hai creato correttamente la casa',
  informazioniGenerali: 'INFORMAZIONI GENERALI',
  caratteristiche: 'CARATTERISTICHE',
  costi: 'COSTI',
  nome: 'Nome',
  indirizzo: 'Indirizzo',
  citta: 'Citta',
  codice_postale: 'Codice postale',
  dataInserimento: 'Data Inserimento',
  locatore: 'Locatore',
  arredamento: 'Arredamento',
  con_arredamento: 'Si + 1 documento allegato',
  senza_arredamento: 'Non arredata',
  dimensione: 'Dimensione',
  camere: 'Camere',
  bagni: 'Bagni',
  con_giardino: 'Con giardino',
  senza_giardino: 'Senza giardino',
  con_posto: 'Con posto auto',
  senza_posto: 'Senza posto auto',
  con_aria: 'Con aria condizionata',
  senza_aria: 'Senza aria condizionata',
  importoAffittoMensile: 'Importo mensile',
  dataInizioContratto: 'Data inizio del contratto',
  dataFineContratto: 'Data fine del contratto',
  durataContratto: 'Durata del contratto',
  modifica_casa: 'Modifica Casa',
  elimina_casa: 'Elimina Casa',
  vuoi_eliminare_casa: 'Vuoi eliminare la casa?',
  tutti_i_dati_casa:
    'Tutti i dati relativi alla casa verranno eliminati definitivamente.',
  casa_eliminata: 'Casa eliminata',
  conferma_eliminazione_casa:
    'Tutti i dati associati alla casa sono stati eliminati',
  salvataggio_modifiche: 'Salvataggio modifiche',
  modifiche_salvate_correttamente:
    'Le modifiche effettuate sono state salvate correttamente',
  aggiungi_tipologia: 'Aggiungi tipologia',
  elimina_tipologia: 'Elimina tipologia',
  tipologia_aggiunta: 'Tipologia aggiunta',
  dati_tipologia_aggiunta: 'Hai aggiunto correttamente la tipologia',
  elimina_dati: 'Vuoi eliminare la seguente tipologia?',
  tipologia_eliminata: 'Tipologia eliminata',
  dati_tipologia_eliminati:
    'Tutti i dati associati alla tipologia sono stati eliminati',
  modifica: 'Modifica',
  informazioni: 'Informazioni',
  carateristiche: 'Caratteristiche',
  affitto: 'Affitto',
  manutenzione: 'Manutenzione',
  aggiungi_locatore: 'Aggiungi locatore',
  inserisci_dati_locatore: 'Inserisci i dati del locatore',
  locatore_creato: 'Locatore creato correttamente',
  dati_locatore_creato: 'Hai creato correttamente il locatore!',
  mia_immagine: 'Immagine',
  tipologia_user: 'Tipologia',
  stato_di_attivita: 'Stato',
  case_associate: 'Case associate',
  localita: 'Locatità',

  anagrafica: 'ANAGRAFICA',
  ruolo: 'RUOLO',
  cognome: 'Cognome',
  mail_personale: 'Mail personale',
  telefono: 'Telefono',
  mail_hint: 'Mail per accesso in piattaforma',
  tipologiaCasa: 'Tipologia',
};

/** Costante per i messaggi di nessun risultato */
export const RESULT_CONSTANT = {
  nessun_risultato: 'Nessun risultato trovato.',
  nessuna_casa: 'Nessuna casa trovata.',
  nessuna_casa_associata: 'Nessuna casa associata',
};
