export const LABEL_CONSTANT = {
  login: 'Login',
  email: 'Email',
  password: 'Password',
  repetPassword: 'Repet password',
  forgot_password: 'Forgot password',
  insert_password: 'Insert a new password',
  new_password: 'New Password',
  welcome: 'Welcome',
  to_website: 'to our new website!',
  send_email: 'An email will be sent to you with steps to follow',
  loading: 'Loading',
  dashboard: 'Dashboard',
  case: 'Case',
  allestimenti: 'Allestimenti',
  prenotazioni: 'Prenotazioni',
  statistiche: 'Statistiche',
  logout: 'Logout',
  profilo: 'Profilo',
  sicuro_di_uscire: 'Vuoi uscire?',
  modifiche_non_salvate: 'I dati inseriti andranno persi.',
  effettua_logout: 'Effettua Logout',
  conferma_logout: 'Sei sicuro di voler effettuare il logout?',
  elimina: 'Elimina',
  aggiungi_casa: 'AGGIUNGI CASA',
  inserisci_dati: 'Inserisci i dati.',
  statoAffitto: 'Stato del affitto',
  statoManutenzione: 'Stato manutenzione',
  arredata: 'Arredata',
  piano: 'Piano',
  tipoRiscaldamento: 'Tipo di riscaldamento',
  giardino: 'Giardino',
  postoAuto: 'Posto auto',
  ariaCondizionata: 'Aria condizionata',
  metodoPagamento: 'Metodo di pagamento',
  trascina_qui: 'Trascina qui le tue immagini o clicca per caricare',
  casa_creata: 'Casa creata correttamente!',
  dati_casa_creata: 'Hai creato correttamente la casa',
  informazioniGenerali: 'INFORMAZIONI GENERALI',
  caratteristiche: 'CARATTERISTICHE',
  costi: 'COSTI',
  nome: 'Nome',
  indirizzo: 'Indirizzo',
  citta: 'Citta',
  codice_postale: 'Codice postale',
  dataDisponibile: 'Data Disponibile',
  locatore: 'Locatore',
  arredamento: 'Arredamento',
  con_arredamento: 'Si + 1 documento allegato',
  senza_arredamento: 'Non arredata',
  dimensione: 'Dimensione',
  camere: 'Camere',
  bagni: 'Bagni',
  con_giardino: 'Con giardino',
  senza_giardino: 'Senza giardino',
  con_posto: 'Con posto auto',
  senza_posto: 'Senza posto auto',
  con_aria: 'Con aria condizionata',
  senza_aria: 'Senza aria condizionata',
  importoAffittoMensile: 'Importo mensile',
  dataInizioContratto: 'Data inizio del contratto',
  dataFineContratto: 'Data fine del contratto',
  durataContratto: 'Durata del contratto',

  anagrafica: 'ANAGRAFICA',
  ruolo: 'RUOLO',
  cognome: 'Cognome',
  mail_personale: 'Mail personale',
  telefono: 'Telefono',
  mail_hint: 'Mail per accesso in piattaforma',
  tipologia: 'Tipologia',
};

/** Costante per i messaggi di nessun risultato */
export const RESULT_CONSTANT = {
  nessun_risultato: 'Nessun risultato trovato.',
};
